services:
    padam87_gls.parcel_api:
        public: true
        autowire: true
        class: Padam87\GlsBundle\Service\ParcelApi
    padam87_gls.tracking_api:
        public: true
        autowire: true
        class: Padam87\GlsBundle\Service\TrackingApi