services:
    Padam87\GlsBundle\Service\ParcelGeneratorManager:
        arguments:
            $generators: !tagged padam87_gls.parcel_genarator

    Padam87\GlsBundle\Service\ParcelApi: ~

    padam87_gls.parcel_api:
        public: true
        alias: Padam87\GlsBundle\Service\ParcelApi
